---
name: Auto Merge Release PR
on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches: [main]
jobs:
  automerge:
    if: github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |-
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            if (pr.data.title.startsWith('chore(main): release')) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });
            }
