---
name: Publish Service Package
on:
  push:
    tags: ['@console-inline/service-v*']
  workflow_dispatch: {}
jobs:
  publish-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        working-directory: packages/service
        run: npm install
      - name: Build package
        working-directory: packages/service
        run: npm run build
      - name: Publish to npm
        working-directory: packages/service
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
