---
name: Publish npm package
on:
  release:
    types: [published]
jobs:
  publish-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org
      - name: Publish packages/service
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |-
          pkg="packages/service"
          if [ -f "$pkg/package.json" ]; then
            echo "Publishing $pkg"
            cd "$pkg"
            npm install
            npm run build || true
            npm publish --access public || true
          else
            echo "Package $pkg not found"
