---
name: Release
on:
  push:
    tags: [v*]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip artifact
        run: |
          zip -r console-inline.nvim.zip . -x "*.git*"
      - name: Generate changelog (simple)
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "See commit history for changes." >> $GITHUB_OUTPUT
          git log -1 --pretty=format:"%s%n%n%b" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: console-inline.nvim.zip
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
